if: tag IS blank
language: node_js
node_js:
  - "10"
script:
  - npm test
  - npm run-script lerna init
  - npm run-script build
deploy:
  provider: script
  script: "npm run-script lerna publish"
  skip_cleanup: true
  on:
    node: "10"
    branch: master

