if: tag IS blank
language: node_js
node_js:
  - "10"
script:
  - npm test
  - npm run-script lerna init
  - npm run-script build
before_deploy:
  - git checkout master
  - git config --local user.name "Travis"
  - git config --local user.email "grzegorz.lipecki@gmail.com"
  - git remote set-url origin "https://${GitHub_Token}@github.com/Consdata/logger.git"
deploy:
  provider: script
  script: "lerna publish --yes"
  skip_cleanup: true
  api_key:
    secure: ${NPM_TOKEN}
  on:
    node: "10"
    branch: master

